name: CI (Branches)

on:
  push:
    branches-ignore: [ "main" ]
    paths:
      - 'src/**'
  pull_request:
    branches-ignore: [ "main" ]
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
